cnpm/binary-mirror-config

package.json

closes cnpm/cnpm#168
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/1)

feat: add grpc mirror

---

package.json
test/index.test.js

closes https://github.com/cnpm/cnpmjs.org/issues/1246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/2)

feat: add PUPPETEER_DOWNLOAD_HOST=https://storage.googleapis.com.cnpmjs.org

---

package.json

NWJS_URLBASE=https://npm.taobao.org/mirrors/nwjs/v
https://github.com/nwjs/npm-installer/blob/master/scripts/install.js#L37
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/3)

feat: support nwjs mirror

---

.travis.yml
LICENSE
README.md
appveyor.yml
package.json
test/index.test.js

skip npm.taobao.org to redirect
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/4)

feat: use cdn url directly

---

package.json

https://github.com/cnpm/mirrors/issues/183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/5)

feat: mirror jpegtran-bin instead of proxy

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/6)

feat: mirrro all iamgemin bins

---

package.json

https://github.com/getsentry/sentry-cli#node
closes https://github.com/cnpm/mirrors/issues/200
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/8)

feat: add SENTRYCLI_CDNURL

---

package.json

已在 cnpm/mirrors 提 PR 并同步过: https://github.com/cnpm/mirrors/pull/204 , 并在 tnpm 中实际测试过
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/9)

添加 canvas-prebuilt 配置

---

package.json

https://npm.taobao.org/mirrors/node-canvas-prebuilt/v2.4.1/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/11)

feat: support canvas binary

---

package.json

https://github.com/swc-project/node-swc/blob/d32b10ce9e7ac147244c88b775f72e45edce2182/src/extensions.js#L239
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/12)

feat: add @swc/core binary mirror site

---

package.json

Reverts cnpm/binary-mirror-config#14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/16)

Revert "fix: delete canvas mirror"

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/17)

feat: add nodejieba mirror

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/18)

feat: add argon2

---

package.json

add ali-zeromq node-pre-gyp-github
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/19)

add ali-zeromq

---

.github/workflows/nodejs.yml
README.md
package.json
test/index.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/binary-mirror-config/20)

feat: change domain to npmmirror.com

---

README.md
package.json

- https://github.com/saucelabs/node-saucectl/pull/13
- https://github.com/cnpm/mirrors/pull/275

📦 NEW: download saucectl binary from China Mirror

---

package.json

https://github.com/cnpm/cnpmcore/pull/100

📦 NEW: Mirror node-gdal-async

---

README.md
package.json

https://github.com/cnpm/cnpmcore/pull/181#issuecomment-1059775229

📦 NEW: Mirror re2 package

---

package.json
test/index.test.js

https://github.com/TryGhost/node-sqlite3/commit/7f744a1dca2664af2fb8957ca68977ba36f134cb
https://github.com/cnpm/cnpmcore/pull/208

🐛 FIX: Use new sqlite3 mirror config

---

.github/workflows/nodejs.yml
index.js
package.json
test/index.test.js

feat: add MirrorConfig class

---

README.md
index.js
package.json
test/index.test.js

https://github.com/cnpm/cnpmcore/pull/232
https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/registry/index.ts#L706

📦 NEW: Use Playwright mirror host

---

package.json

https://github.com/cnpm/cnpmcore/pull/259

📦 NEW: Use skia-canvas China Mirrors

---

package.json

https://github.com/cnpm/npminstall/pull/407

📦 NEW: Mirror wrtc

---

package.json

https://github.com/cnpm/cnpmcore/pull/296

📦 NEW: Mirror better-sqlite3
